const HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'x-franchisehq-export-token'};
const slugPattern=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:HEADERS});
const slugOf=c=>String(c.params?.leagueSlug||'').trim().toLowerCase();
const metaKey=s=>`league:${s}:companion:latest`;
const tokenKey=s=>`league:${s}:companion:export-token`;
async function expectedToken(env,slug){const kv=env.LEAGUE_CONFIG?.get?await env.LEAGUE_CONFIG.get(tokenKey(slug)):null;return kv||env.COMPANION_EXPORT_TOKEN||null;}
function suppliedToken(request){const url=new URL(request.url);return request.headers.get('x-franchisehq-export-token')||url.searchParams.get('token')||'';}
function safeEqual(a,b){const x=new TextEncoder().encode(String(a||'')),y=new TextEncoder().encode(String(b||''));if(x.length!==y.length||!x.length)return false;let m=0;for(let i=0;i<x.length;i++)m|=x[i]^y[i];return m===0;}
function kind(v){if(Array.isArray(v))return 'array';if(v===null)return 'null';return typeof v;}
function summarizeObject(value){if(!value||typeof value!=='object'||Array.isArray(value))return null;return {keys:Object.keys(value).slice(0,100),fieldTypes:Object.fromEntries(Object.entries(value).slice(0,100).map(([k,v])=>[k,kind(v)]))};}
function collectionCandidates(root){const found=[];const walk=(obj,path,depth)=>{if(depth>3||!obj||typeof obj!=='object')return;for(const [key,val] of Object.entries(obj)){const next=path?`${path}.${key}`:key;if(Array.isArray(val)){const first=val.find(x=>x&&typeof x==='object'&&!Array.isArray(x));found.push({path:next,count:val.length,item: summarizeObject(first)});}else if(val&&typeof val==='object'){walk(val,next,depth+1);}}};walk(root,'',0);return found.slice(0,60);}
function likelyFields(keys=[]){const match=(terms)=>keys.filter(k=>terms.some(t=>k.toLowerCase().includes(t))).slice(0,20);return {ids:match(['id','assetname']),teamAssignments:match(['team','club','roster']),names:match(['name','first','last']),positions:match(['position','pos']),ratings:match(['overall','ovr','rating']),development:match(['dev','trait']),status:match(['injury','status','reserve'])};}
function analyze(payload,meta){const root=summarizeObject(payload)||{keys:[],fieldTypes:{}};const collections=collectionCandidates(payload).map(c=>({...c,likelyFields:likelyFields(c.item?.keys||[])}));return {exportId:meta.exportId,receivedAt:meta.receivedAt,byteLength:meta.byteLength,season:meta.season,week:meta.week,topLevel:root,collections,rawPayloadReturned:false,activationPerformed:false};}
export async function onRequestOptions(){return new Response(null,{status:204,headers:HEADERS});}
export async function onRequestGet(context){const slug=slugOf(context);if(!slugPattern.test(slug))return json({ok:false,error:'Invalid league slug.'},400);if(!context.env.COMPANION_EXPORTS?.get||!context.env.COMPANION_EXPORT_META?.get)return json({ok:false,error:'Companion receiver storage is not configured.'},503);const token=await expectedToken(context.env,slug);if(!token)return json({ok:false,error:'No export token is configured for this league.'},503);if(!safeEqual(suppliedToken(context.request),token))return json({ok:false,error:'Unauthorized inspection request.'},401);const meta=await context.env.COMPANION_EXPORT_META.get(metaKey(slug),{type:'json'});if(!meta?.r2ObjectKey)return json({ok:false,error:'No pending Companion export is available.'},404);const object=await context.env.COMPANION_EXPORTS.get(meta.r2ObjectKey);if(!object)return json({ok:false,error:'The pending export payload could not be found.'},404);let payload;try{payload=JSON.parse(await object.text());}catch(_){return json({ok:false,error:'Stored export is not valid JSON.'},422);}return json({ok:true,leagueSlug:slug,inspection:analyze(payload,meta)});}
