(function initGamesService(global){
  'use strict';
  const HQ=global.FranchiseHQ=global.FranchiseHQ||{};
  const KEY='franchisehq:confidence-pool:v1';
  const clone=v=>JSON.parse(JSON.stringify(v));
  const freeze=v=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v)}return v};
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{seasons:{}}}catch{return{seasons:{}}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const games=()=>global.FGC_APP?.schedule||[];
  const seasonId=()=>String(global.FGC_APP?.leagueYear?.()||2026);
  const account=()=>global.FGC_TRADE?.getCurrentAccount?.()||{id:'commissioner',name:'Commissioner',teamId:'dal',role:'commissioner'};
  function ensure(){const s=read(),id=seasonId();if(!s.seasons[id])s.seasons[id]={season:id,status:'open',openedAt:new Date().toISOString(),lockedAt:null,entries:{}};write(s);return s}
  function config(){const s=ensure(),c=s.seasons[seasonId()];return freeze(clone(c))}
  function setStatus(status){if(!['open','locked','final'].includes(status))throw new Error('Invalid pool status');const s=ensure(),c=s.seasons[seasonId()];c.status=status;c[status==='open'?'openedAt':status==='locked'?'lockedAt':'finalizedAt']=new Date().toISOString();write(s);return config()}
  function allGames(){return freeze(games().flatMap(w=>w.games.map(g=>({...g,season:seasonId(),phase:'regular'}))))}
  function getWeek(week){const w=games().find(x=>Number(x.week)===Number(week));return freeze(clone(w||{week:Number(week),games:[]}))}
  function getGame(id){return allGames().find(g=>g.id===id)||null}
  function getTeamSchedule(teamId){return freeze(allGames().filter(g=>g.homeId===teamId||g.awayId===teamId))}
  function currentWeek(){return games().find(w=>w.games.some(g=>g.status==='live'))?.week||games().find(w=>w.games.some(g=>g.status==='scheduled'))?.week||games().at(-1)?.week||1}
  function entry(userId=account().id){const s=ensure(),c=s.seasons[seasonId()];return freeze(clone(c.entries[userId]||{userId,season:seasonId(),status:'draft',picks:{},updatedAt:null,submittedAt:null}))}
  function savePick(gameId,selectedTeamId,confidence,userId=account().id){const s=ensure(),c=s.seasons[seasonId()];if(c.status!=='open')return{ok:false,error:'Confidence Pool submissions are locked.'};const game=getGame(gameId);if(!game||![game.homeId,game.awayId].includes(selectedTeamId))return{ok:false,error:'Choose a valid team.'};const week=String(game.week),value=Number(confidence);if(!Number.isInteger(value)||value<1||value>getWeek(game.week).games.length)return{ok:false,error:'Choose a valid confidence value.'};const e=c.entries[userId]||{userId,season:seasonId(),status:'draft',picks:{}};for(const [id,p] of Object.entries(e.picks)){if(id!==gameId&&String(p.week)===week&&Number(p.confidence)===value)return{ok:false,error:`Confidence ${value} is already used in Week ${week}.`}}e.picks[gameId]={gameId,week:game.week,selectedTeamId,confidence:value};e.updatedAt=new Date().toISOString();c.entries[userId]=e;write(s);return{ok:true,entry:entry(userId)}}
  function autoAssign(week,userId=account().id){const s=ensure(),c=s.seasons[seasonId()];if(c.status!=='open')return{ok:false,error:'Confidence Pool submissions are locked.'};const e=c.entries[userId]||{userId,season:seasonId(),status:'draft',picks:{}};getWeek(week).games.forEach((g,i)=>{const existing=e.picks[g.id];e.picks[g.id]={gameId:g.id,week:g.week,selectedTeamId:existing?.selectedTeamId||g.homeId,confidence:i+1}});e.updatedAt=new Date().toISOString();c.entries[userId]=e;write(s);return{ok:true,entry:entry(userId)}}
  function validateEntry(userId=account().id){const e=entry(userId),issues=[];games().forEach(w=>{const vals=[];w.games.forEach(g=>{const p=e.picks[g.id];if(!p)issues.push(`Week ${w.week}: missing ${g.id}`);else vals.push(p.confidence)});if(new Set(vals).size!==vals.length)issues.push(`Week ${w.week}: duplicate confidence values`)});return freeze({valid:issues.length===0,issues,totalGames:allGames().length,picked:Object.keys(e.picks).length})}
  function submit(userId=account().id){const valid=validateEntry(userId);if(!valid.valid)return{ok:false,error:'Complete every game and use each weekly confidence value once.',validation:valid};const s=ensure(),c=s.seasons[seasonId()],e=c.entries[userId];e.status='submitted';e.submittedAt=new Date().toISOString();write(s);return{ok:true,entry:entry(userId)}}
  function score(userId=account().id){const e=entry(userId);let total=0,correct=0;const weeks={};allGames().forEach(g=>{const p=e.picks[g.id];if(!p)return;const final=g.status==='final';const winner=final?(g.homeScore===g.awayScore?'tie':g.homeScore>g.awayScore?g.homeId:g.awayId):null;const points=!final?0:winner==='tie'?p.confidence/2:winner===p.selectedTeamId?p.confidence:0;if(points>0&&winner!=='tie')correct++;total+=points;(weeks[g.week]||(weeks[g.week]={week:g.week,points:0,correct:0,finalGames:0})).points+=points;if(points>0&&winner!=='tie')weeks[g.week].correct++;if(final)weeks[g.week].finalGames++});return freeze({userId,totalPoints:total,correctPicks:correct,weeks:Object.values(weeks)})}
  function leaderboard(){const s=ensure(),c=s.seasons[seasonId()];const accounts=global.FGC_TRADE?.accounts||[];return freeze(Object.keys(c.entries).map(id=>{const a=accounts.find(x=>x.id===id)||{id,name:id,teamId:null};return{...score(id),name:a.handle||a.name||id,teamId:a.teamId,status:c.entries[id].status}}).sort((a,b)=>b.totalPoints-a.totalPoints))}
  function diagnostics(){const c=config();return freeze({service:'games',version:'5.6.0',season:c.season,poolStatus:c.status,gameCount:allGames().length,currentWeek:currentWeek(),entryCount:Object.keys(c.entries).length})}
  const service={getSeason:()=>freeze({id:seasonId(),phase:'regular',currentWeek:currentWeek()}),getWeek,getGame,getTeamSchedule,getUpcomingGames:()=>freeze(allGames().filter(g=>g.status==='scheduled')),getCompletedGames:()=>freeze(allGames().filter(g=>g.status==='final')),getCurrentWeek:currentWeek,getAllGames:allGames,confidence:{config,setStatus,getEntry:entry,savePick,autoAssign,validateEntry,submit,score,leaderboard},diagnostics};
  if(HQ.defineModuleService)HQ.defineModuleService('league','games',service,{alias:'leagueGames',replace:true});else{HQ.modules=HQ.modules||{};HQ.modules.league=HQ.modules.league||{};HQ.modules.league.games=service;HQ.leagueGames=service}
})(window);
