(() => {
  'use strict';
  const HQ = window.FranchiseHQ;
  if (!HQ?.defineModuleService || !HQ.leagueRepository || !HQ.leagueTenant) throw new Error('League repository and tenant service must load before snapshot-manager.js.');
  const VERSION='5.9.1.3', BASE_KEY='franchisehq.import.snapshots.v2', MAX_RETAINED=10;
  const memories=new Map(), listeners=new Set();
  const clone=v=>v==null?v:(typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v)));
  const freeze=(v,seen=new WeakSet())=>{if(!v||typeof v!=='object'||seen.has(v))return v;seen.add(v);Object.getOwnPropertyNames(v).forEach(k=>freeze(v[k],seen));return Object.freeze(v);};
  const now=()=>new Date().toISOString();
  const leagueId=options=>options?.leagueId||HQ.leagueTenant.current().id;
  const key=id=>HQ.leagueTenant.scopedKey(BASE_KEY,id);
  function empty(){return{candidates:new Map(),retained:[],activeId:null,sequence:0};}
  function memory(id=leagueId()){if(!memories.has(id)){const m=empty();try{let raw=localStorage.getItem(key(id));if(!raw&&id===HQ.leagueTenant.DEFAULT_LEAGUE.id){raw=localStorage.getItem('franchisehq.import.snapshots.v1');if(raw)localStorage.setItem(key(id),raw);}const p=JSON.parse(raw||'null');if(p){m.retained=Array.isArray(p.retained)?p.retained.map(x=>({...x,leagueId:id})).slice(0,MAX_RETAINED):[];m.activeId=p.activeId||null;m.sequence=Number.isFinite(p.sequence)?p.sequence:m.retained.length;}}catch(_){}memories.set(id,m);}return memories.get(id);}
  function persist(id){const m=memory(id);try{localStorage.setItem(key(id),JSON.stringify({retained:m.retained,activeId:m.activeId,sequence:m.sequence}));return true;}catch(e){console.warn('[snapshotManager] persistence unavailable',e);return false;}}
  function makeId(){return `candidate-${crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;}
  function counts(s){const out={};['teams','players','schedule','games','standings','statistics','transactions'].forEach(k=>{if(Array.isArray(s?.[k]))out[k]=s[k].length;else if(s?.[k]&&typeof s[k]==='object')out[k]=Object.keys(s[k]).length;});return out;}
  function summary(r){return r?freeze({id:r.id,leagueId:r.leagueId,version:r.version,status:r.status,source:r.source,importId:r.importId,season:r.season,week:r.week,createdAt:r.createdAt,activatedAt:r.activatedAt||null,rejectedAt:r.rejectedAt||null,rejectionReason:r.rejectionReason||null,recordCounts:freeze(clone(r.recordCounts||{}))}):null;}
  function publish(type,r,extra={}){const payload=freeze({type,leagueId:r?.leagueId||extra.leagueId||leagueId(),snapshot:summary(r),timestamp:now(),...clone(extra)});listeners.forEach(fn=>{try{fn(payload);}catch(e){console.error('[snapshotManager] listener failed',e);}});HQ.events?.emit?.('snapshot:changed',payload,{source:'leagueSnapshotManager'});window.dispatchEvent(new CustomEvent('franchisehq:snapshot-changed',{detail:payload}));return payload;}
  function createSnapshot(snapshot,metadata={}){const id=leagueId(metadata),m=memory(id),sid=metadata.snapshotId||makeId();if(!snapshot||typeof snapshot!=='object')throw new TypeError('Snapshot data must be an object.');if(m.candidates.has(sid)||m.retained.some(x=>x.id===sid))throw new Error(`Snapshot ID already exists: ${sid}`);const record=freeze({id:sid,leagueId:id,version:++m.sequence,status:'candidate',source:metadata.source||snapshot.source?.provider||snapshot.source?.source||'madden-companion',importId:metadata.importId||snapshot.source?.importId||null,season:metadata.season??snapshot.season??snapshot.meta?.season??null,week:metadata.week??snapshot.week??snapshot.meta?.week??null,createdAt:now(),activatedAt:null,rejectedAt:null,rejectionReason:null,recordCounts:counts(snapshot),snapshot:freeze(clone({...snapshot,meta:{...(snapshot.meta||{}),leagueId:id}})),validation:metadata.validation?freeze(clone(metadata.validation)):null});m.candidates.set(sid,record);persist(id);publish('candidate-created',record);return summary(record);}
  function find(id,options={}){const lid=leagueId(options),m=memory(lid);return m.candidates.get(id)||m.retained.find(x=>x.id===id)||null;}
  function getSnapshot(id,options={}){const r=find(id,options);return r?(options.includeData?freeze(clone(r)):summary(r)):null;}
  function getCandidateSnapshot(options={}){const vals=[...memory(leagueId(options)).candidates.values()];return summary(vals.at(-1)||null);}
  function getActiveSnapshot(options={}){const m=memory(leagueId(options)),r=m.retained.find(x=>x.id===m.activeId)||null;return r?(options.includeData?freeze(clone(r)):summary(r)):null;}
  function activateSnapshot(id,options={}){const lid=leagueId(options),m=memory(lid),c=m.candidates.get(id);if(!c)throw new Error(`Candidate snapshot not found: ${id}`);if(options.validated!==true)throw new Error('Candidate snapshots may only be activated after validation.');const previous=m.retained.find(x=>x.id===m.activeId)||null,active=freeze({...clone(c),status:'active',activatedAt:now()});if(active.snapshot?.source?.source==='madden')HQ.leagueRepository.install(active.snapshot,{validated:true,receipt:options.validation||active.validation});m.candidates.delete(id);m.activeId=id;m.retained=[active,...m.retained.filter(x=>x.id!==id)].slice(0,MAX_RETAINED);persist(lid);publish('snapshot-activated',active,{previousSnapshotId:previous?.id||null});return summary(active);}
  function rejectSnapshot(id,reason='Snapshot rejected.',options={}){const lid=leagueId(options),m=memory(lid),c=m.candidates.get(id);if(!c)return null;const r=freeze({...clone(c),status:'rejected',rejectedAt:now(),rejectionReason:String(reason),snapshot:null});m.candidates.delete(id);persist(lid);publish('snapshot-rejected',r);return summary(r);}
  function rollbackSnapshot(id,options={}){const lid=leagueId(options),m=memory(lid),target=m.retained.find(x=>x.id===id);if(!target)throw new Error(`Retained snapshot not found: ${id}`);if(options.authorized!==true)throw new Error('Snapshot rollback requires explicit authorization.');const prev=m.activeId,active=freeze({...clone(target),status:'active',activatedAt:now()});m.retained=[active,...m.retained.filter(x=>x.id!==id)].slice(0,MAX_RETAINED);m.activeId=id;persist(lid);publish('snapshot-rolled-back',active,{previousSnapshotId:prev});return summary(active);}
  function deleteSnapshot(id,options={}){const lid=leagueId(options),m=memory(lid);if(id===m.activeId)throw new Error('The active snapshot cannot be deleted.');const a=m.candidates.delete(id),before=m.retained.length;m.retained=m.retained.filter(x=>x.id!==id);persist(lid);return a||before!==m.retained.length;}
  function listSnapshots(options={}){return freeze(memory(leagueId(options)).retained.map(summary));}
  function listCandidates(options={}){return freeze([...memory(leagueId(options)).candidates.values()].map(summary));}
  function subscribe(fn,options={}){listeners.add(fn);if(options.immediate)fn(freeze({type:'snapshot-status',leagueId:leagueId(options),snapshot:getActiveSnapshot(options),timestamp:now()}));return()=>listeners.delete(fn);}
  function resetDevelopmentState(options={}){const lid=leagueId(options);memories.set(lid,empty());try{localStorage.removeItem(key(lid));}catch(_){}publish('snapshot-state-reset',null,{leagueId:lid});return diagnostics({leagueId:lid});}
  function diagnostics(options={}){const lid=leagueId(options),m=memory(lid);return freeze({service:'leagueSnapshotManager',version:VERSION,leagueId:lid,activeSnapshotId:m.activeId,candidateCount:m.candidates.size,retainedCount:m.retained.length,maxRetained:MAX_RETAINED,persistence:'league-scoped-localStorage',immutableSnapshots:true,guardedActivation:true,rollbackAvailable:true});}
  HQ.defineModuleService('league','leagueSnapshotManager',{createSnapshot,getSnapshot,getCandidateSnapshot,getActiveSnapshot,activateSnapshot,rejectSnapshot,rollbackSnapshot,deleteSnapshot,listSnapshots,listCandidates,subscribe,resetDevelopmentState,diagnostics},{replace:true,alias:'leagueSnapshotManager'});
  HQ.manifest?.register?.({scope:'module',module:'league',id:'league-snapshot-manager',service:'leagueSnapshotManager',script:'league-engine/snapshot-manager.js',version:VERSION,dependencies:['leagueTenant'],capabilities:['league-scoped-snapshots','candidate-snapshots','guarded-activation','rollback','persistent-metadata']});
})();
